package Minilla::CLI::Dist;
use strict;
use warnings;
use utf8;

use File::Spec::Functions qw(catfile);
use File::Basename qw(basename);
use File::Copy qw(copy);

use Minilla::Project;
use Minilla::WorkDir;
use Minilla::Util qw(check_git parse_options);

sub run {
    my ($self, @args) = @_;

    my $test         = 1;
    my $skip_prepare = 0;

    check_git;

    parse_options(
        \@args,
        'test!'         => \$test,
        'skip-prepare!' => \$skip_prepare,
    );

    my $project = Minilla::Project->new();
    unless ($project->validate()) {
        return;
    }
    my $work_dir = Minilla::WorkDir->new(
        project      => $project,
        file_modes   => $project->file_modes,
        skip_prepare => $skip_prepare,
    );
    if ($test) {
        local $ENV{RELEASE_TESTING} = 1;
        $work_dir->dist_test();
    }
    my $tar = $work_dir->dist();
    my $dst = catfile($project->dir, basename($tar));
    copy($tar, $dst);
}

1;
__END__

=head1 NAME

Minilla::CLI::Dist - Make tar ball distribution

=head1 SYNOPSIS

    % minil dist
    % minil dist --skip-prepare

=head1 OPTIONS

=over 4

=item B<--no-test>, B<--notest>

Skip distribution tests. Both spellings are supported.

=item B<--skip-prepare>

Use files generated by C<minil prepare> instead of regenerating them.

=back

=head1 DESCRIPTION

This sub-command makes distribution tar ball.

With C<--skip-prepare>, files generated by C<minil prepare>, including
F<META.json>, F<README.md>, and F<Build.PL> or F<Makefile.PL>, are copied
from the prepared source tree without being regenerated. Packaging files
such as F<META.yml> and F<MANIFEST> are still generated.

To make distribution archives reproducible, Minilla uses the timestamp of
the Git HEAD commit for every tar entry when available. If
C<SOURCE_DATE_EPOCH> is set, Minilla follows the reproducible-build convention
and uses its value instead. In either case, tar metadata and the gzip header
are canonicalized so identical distribution inputs produce identical
archives. If neither timestamp is available, Minilla retains its legacy
archive behavior.
