package Minilla::CLI::Release;
use strict;
use warnings;
use utf8;
use ExtUtils::MakeMaker qw(prompt);

use Minilla::Util qw(edit_file require_optional parse_options);
use Minilla::WorkDir;
use Minilla::Logger;
use Minilla::Project;

sub run {
    my ($self, @args) = @_;

    my $opts = {
        test         => 1,
        trial        => 0,
        dry_run      => 0,
        skip_prepare => 0,
    };
    parse_options(
        \@args,
        'test!'         => \$opts->{test},
        'trial!'        => \$opts->{trial},
        'dry-run!'      => \$opts->{dry_run},
        'skip-prepare!' => \$opts->{skip_prepare},
        'pause-config=s' => \$opts->{pause_config},
    );

    my $project = Minilla::Project->new(
        skip_prepare => $opts->{skip_prepare},
    );
    unless ($project->validate()) {
        return;
    }

    my @steps = _steps($project);
    my @klasses;
    # Load all step classes.
    for (@steps) {
        my $klass = "Minilla::Release::$_";
        if (eval "require ${klass}; 1") {
            push @klasses, $klass;
            $klass->init() if $klass->can('init');
        } else {
            errorf("Error while loading %s: %s\n", $_, $@);
        }
    }
    # And run all steps.
    for my $klass (@klasses) {
        $klass->run($project, $opts);
    }
}

sub _steps {
    my $project = shift;

    my @steps = qw(
        CheckUntrackedFiles
        CheckOrigin
        CheckReleaseBranch
        BumpVersion
        CheckChanges
        RegenerateFiles
        RunHooks
        DistTest
        MakeDist

        UploadToCPAN

        RewriteChanges
        Commit
        Tag
    );

    return @steps if $project->manage_changes;
    return grep { $_ ne 'CheckChanges' && $_ ne 'RewriteChanges' } @steps;
}

1;
__END__

=head1 NAME

Minilla::CLI::Release - Release the module to CPAN!

=head1 SYNOPSIS

    % minil release

=head1 OPTIONS

=over 4

=item B<--no-test>, B<--notest>

Skip distribution tests. Both spellings are supported.

=item B<--trial>

Create a trial release.

=item B<--dry-run>

Run the release process without bumping the version, committing, tagging, or
uploading to CPAN.

=item B<--skip-prepare>

Use files generated by C<minil prepare> instead of regenerating them.

=item B<--pause-config FILE>

Use FILE as the CPAN::Uploader configuration file.

=back

=head1 DESCRIPTION

This sub-command release the module to CPAN.

=head1 ENVIRONMENT VARIABLES

=over 4

=item FAKE_RELEASE

    > FAKE_RELEASE=1 minil release

If this is your first conversion to Minilla and want to make sure you're not going to mess CPAN with a bad archive when something goes wrong, you can run the release command with FAKE_RELEASE environment variable. This will run all the other release process, except the UploadToCPAN step.

Note, this runs C<< git tag >> and C<< git push >>.

=back
